parameters:
  database.sqlite:
    driver: pdo_sqlite
    path: ../db.sqlite
  database.mysql:
    driver: pdo_mysql
    host: localhost
    dbname: app
    user: admin
    password: admin
  database.migrations:
    path: migrations
    namespace: DoctrineMigrations
    table: doctrine_migration_versions
    name: Doctrine Migrations