imports:
    - { resource: 'database.yml' }
    - { resource: 'doctrine.yml' }
    - { resource: 'serializer.yml' }
    - { resource: 'mail.yml' }
parameters:
  core: &core.default
    mode: dev
    log.enabled: true,
    log.level: error
  routers:
    - router.rest
    - router.media