services:
  app:
    class: Neochic\SlimTools\Core\App
    arguments:
      - %core%
      - @slim
  console:
    class: Neochic\SlimTools\Core\Console
    arguments:
      - %database.migrations%
      - @entity_manager
  slim:
    class: Slim\Slim
  session:
    class: Neochic\SlimTools\Misc\Session
  jsonResponse:
    class: Neochic\SlimTools\Misc\JsonResponse
  validator:
    class: Neochic\SlimTools\Core\Validator
  entity_manager.factory:
    class: Neochic\SlimTools\Factory\EntityManagerFactory
  entity_manager:
    class: Doctrine\ORM\EntityManager
    factory: [@entity_manager.factory, createEntityManager]
    arguments:
      - %database.mysql%
      - %doctrine%
  view.json:
    class: Neochic\SlimTools\View\Json
    arguments:
      - @serializer
  router.rest:
    class: Neochic\SlimTools\Router\RestRouter
    arguments:
      - @app
      - @slim
      - @view.json
  controller:
    abstract: true
    arguments:
      - @slim
      - @entity_manager
  serializer.builder.factory:
    class: JMS\Serializer\SerializerBuilder
  serializer.builder:
    class: JMS\Serializer\SerializerBuilder
    factory: [@serializer.builder.factory, create]
  serializer.factory:
    class: Neochic\SlimTools\Factory\SerializerFactory
  serializer:
    class: JMS\Serializer\Serializer
    factory: [@serializer.factory, createSerializer]
    arguments:
      - %serializer%
      - @serializer.builder